name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  job1:
    uses: ./.github/workflows/call-ed.yaml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
